<?php

use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public $arg = [];
    public $company_name = '';
    public $email = 'xyz@gmail.com';
    public $contact = '+9000 000 000';
    public $postcode = '';
    public $address = '';
    public $cmp_reg_number = 'XYZ0123456';
    public $fca_reg_number = 'XYZ0123456';
    public $vat_number = 'XYZ0123456';
    public $ico_number = 'XYZ0123456';

    public function __construct($arg = [])
    {
        $this->arg = $arg;
        $user = \App\User::find($arg['user_id']);
        if (!is_null($user)) {
            $this->company_name = $user->company_name ?? '';
            $this->email = $user->email ?? 'xyz@gmail.com';
            $this->contact = ($user->country_code . $user->mobile) ?? '+9000 000 000';
            $this->postcode = $user->postcode ?? '';
            $this->address = $user->address ?? '';
            $this->cmp_reg_number = $user->cmp_reg_number ?? 'XYZ0123456';
            $this->fca_reg_number = $user->fca_reg_number ?? 'XYZ0123456';
            $this->vat_number = $user->vat_number ?? 'XYZ0123456';
            $this->ico_number = $user->ico_number ?? 'XYZ0123456';
        }
    }

    public function run()
    {


        $values = $this->getDataByTemplate();
        foreach ($values as $key => $value) {
            DB::table('web_content_details')->insert($value);
        }
        \App\WebService::where(['user_id' => $this->arg['user_id'], 'website_id' => $this->arg['website_id']])->delete();
        $services = $this->getServices();
        foreach ($services as $key => $value) {
            DB::table('web_services')->insert($value);
        }
        \App\WebTestimonial::where(['user_id' => $this->arg['user_id'], 'website_id' => $this->arg['website_id']])->delete();
        $testimonial = $this->getTestimonial();
        foreach ($testimonial as $key => $value) {
            DB::table('web_testimonials')->insert($value);
        }
        \App\WebRecentStock::where(['user_id' => $this->arg['user_id'], 'website_id' => $this->arg['website_id']])->delete();
        $recentStock = $this->getRecentStock();
        foreach ($recentStock as $key => $value) {
            DB::table('web_recent_stocks')->insert($value);
        }
        \App\WebWorkingHours::where(['user_id' => $this->arg['user_id'], 'website_id' => $this->arg['website_id']])->delete();
        $workingHours = $this->getWorkingHours();
        foreach ($workingHours as $key => $value) {
            DB::table('web_working_hours')->insert($value);
        }
    }

    public function getDataByTemplate()
    {
        $data = [];

        $data = [
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'landline_1',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'landline_2',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'landline',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'email',
                'value' => $this->email,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'top_header',
                'key' => 'address',
                'value' => $this->address,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'mobile',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'address',
                'value' => $this->address,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'contact_us',
                'section_slug' => 'middle_content',
                'key' => 'landline',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'contact_us',
                'section_slug' => 'middle_content',
                'key' => 'email',
                'value' => $this->email,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'contact_us',
                'section_slug' => 'middle_content',
                'key' => 'address',
                'value' => $this->address,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'top_header',
                'key' => 'mobile',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'header',
                'key' => 'logo',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/logo.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'slider',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/home-banner-bg.jpg'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'slider',
                'key' => 'slider_image_1',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/home-banner-car1.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'slider',
                'key' => 'slider_image_2',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/home-banner-car2.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'slider',
                'key' => 'slider_image_3',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/home-banner-car3.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'slider',
                'key' => 'title',
                'value' => 'Welcome to AtoZ Cars',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'slider',
                'key' => 'sub_title',
                'value' => 'A wide range of vehicles and services to suit you, take a look around & find you ideal car',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'sub_title',
                'value' => 'We take quality and our customer service serious!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'title',
                'value' => 'About Us',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'description',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-img.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'our_services',
                'key' => 'title',
                'value' => 'Our Services',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'our_services',
                'key' => 'sub_title',
                'value' => 'Our aim is to make sure your car buying experience is as smooth as it can be! Have a look below at the services we are able to provide or give us a call today and ask a member on offers on our products and services!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'our_services',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/our-services.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'testimonials',
                'key' => 'title',
                'value' => 'Testimonials',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'testimonials',
                'key' => 'sub_title',
                'value' => 'We take aftersales and services serious! Have a look below at some of the reviews we have received from our customers!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'our_recent_stock',
                'key' => 'title',
                'value' => 'Our Recent Stock',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'our_recent_stock',
                'key' => 'sub_title',
                'value' => 'Browse through our most recently sold stock to have an idea on the vehicle we sell or to help you narrow down your car search!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'offer',
                'key' => 'title',
                'value' => 'We offer competitive finance plans to suit your budget and needs!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'offer',
                'key' => 'sub_title',
                'value' => 'With payment options ranging from 1 to 5 years we are able to help you buy your dream car today at a price plan that is suitable for you! Click the link below to read more on our finance options or if you wish to submit an application and see whether or not you are eligible for finance.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'offer',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/offer_img.jpg'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'footer_text',
                'value' => $this->address,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'footer_logo',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/logo.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'vat_number',
                'value' => $this->vat_number,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'company_registration_number',
                'value' => $this->cmp_reg_number,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'fca_number',
                'value' => $this->fca_reg_number,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'email_address',
                'value' => $this->email,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'contact_number',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box1',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-icon1.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box2',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-icon2.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box3',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-icon3.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box1',
                'key' => 'title',
                'value' => 'EXCLUSIVE',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box2',
                'key' => 'title',
                'value' => 'SECURE',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box3',
                'key' => 'title',
                'value' => 'update',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box1',
                'key' => 'description',
                'value' => 'Luxury cars – a class comprised in significant proportion of large traditional limousine saloons with one or two oversized',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box2',
                'key' => 'description',
                'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Viverra faucibus turpis etiam ',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us_box3',
                'key' => 'description',
                'value' => 'Luxury cars – a class comprised in significant proportion of large traditional limousine saloons with one or two oversized ',
                'input_type' => 'text',
            ], [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars1',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/upcoming-slide1.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars2',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/upcoming-slide2.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars3',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/upcoming-slide3.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars4',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/upcoming-slide2.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars1',
                'key' => 'title',
                'value' => 'Nissan GTR 350',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars2',
                'key' => 'title',
                'value' => 'Masda X7',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars3',
                'key' => 'title',
                'value' => 'Mastang GT 200',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars4',
                'key' => 'title',
                'value' => 'Mastang GT 200',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars1',
                'key' => 'date',
                'value' => 'September 5 2021',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars2',
                'key' => 'date',
                'value' => 'September 5 2021',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars3',
                'key' => 'date',
                'value' => 'September 5 2021',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'upcoming_cars4',
                'key' => 'date',
                'value' => 'September 5 2021',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'footer_address',
                'value' => $this->address,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'footer_email',
                'value' => $this->email,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'common',
                'section_slug' => 'footer',
                'key' => 'footer_mobile',
                'value' => $this->contact,
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category1',
                'key' => 'title',
                'value' => 'car',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category1',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/car1.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category2',
                'key' => 'title',
                'value' => 'car',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category2',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/car2.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category3',
                'key' => 'title',
                'value' => 'car',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category3',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/car3.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category4',
                'key' => 'title',
                'value' => 'car',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category4',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/car4.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category5',
                'key' => 'title',
                'value' => 'car',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category5',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/car5.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category6',
                'key' => 'title',
                'value' => 'car',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'car_category6',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/car6.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_image_1',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-img1.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_image_2',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-img2.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_image_3',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-img3.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_image_4',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-img4.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_image_5',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-img5.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_image_6',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/about-img6.png'),
                'input_type' => 'file',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_title_1',
                'value' => 'WE TAKE QUALITY AND OUR CUSTOMER SERVICE SERIOUS!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_title_2',
                'value' => 'WE TAKE QUALITY AND OUR CUSTOMER SERVICE SERIOUS!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_title_3',
                'value' => 'WE TAKE QUALITY AND OUR CUSTOMER SERVICE SERIOUS!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_title_4',
                'value' => 'WE TAKE QUALITY AND OUR CUSTOMER SERVICE SERIOUS!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_title_5',
                'value' => 'WE TAKE QUALITY AND OUR CUSTOMER SERVICE SERIOUS!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_title_6',
                'value' => 'WE TAKE QUALITY AND OUR CUSTOMER SERVICE SERIOUS!',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_description_1',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_description_2',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_description_3',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_description_4',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_description_5',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'about_us',
                'key' => 'category_description_6',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'welcome',
                'key' => 'title',
                'value' => 'Welcome to A to Z',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'welcome',
                'key' => 'sub_title',
                'value' => 'If you are looking for a reliable car for you or your family in the “Hounslow” area look no further. At “AtoZ cars Ltd” we take quality and our customer service serious! With many years of experience and a driven sales team we aim to provide you with the car and the service you deserve! Great savings, quality stock and a reliable and responsive after sales service makes buying from “AtoZ cars ltd” a dream come true.',
                'input_type' => 'text',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'templete_slug' => $this->arg['template_slug'],
                'page_slug' => 'home',
                'section_slug' => 'welcome',
                'key' => 'image',
                'value' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/home/welcomecar.png'),
                'input_type' => 'file',
            ],
        ];
        return $data;
    }

    public function getServices()
    {
        $data = [];

        $data = [
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Part Exchange or Sell Your Vehicle',
                'description' => '',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/our-services1.png'),
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Finance',
                'description' => '',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/our-services2.png'),
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Warranty',
                'description' => '',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/our-services3.png'),
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Service And Repairs',
                'description' => '',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/our-services4.png'),
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Bodyshop',
                'description' => '',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/our-services5.png'),
            ]
        ];

        return $data;
    }

    public function getTestimonial()
    {
        $data = [];
        $data = [
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Savannah Nguyen',
                'description' => 'Excellent in terms of Safety, Handling and Performance in comparison with other hatchbacks. I have used i20 as well but its not even near to VW. Now using Altroz , which is at par with VW i',
                'label' => 'Excellent Work',
                'author_name' => 'Savannah Nguyen',
                'author_image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/client1.png'),
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Guy Hawkins',
                'description' => 'Excellent in terms of Safety, Handling and Performance in comparison with other hatchbacks. I have used i20 as well but its not even near to VW. Now using Altroz , which is at par with VW i',
                'label' => 'Excellent Work',
                'author_name' => 'Guy Hawkins',
                'author_image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/client2.png'),
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Robert Fox',
                'description' => 'Excellent in terms of Safety, Handling and Performance in comparison with other hatchbacks. I have used i20 as well but its not even near to VW. Now using Altroz ',
                'label' => 'Great Job!!!',
                'author_name' => 'Robert Fox',
                'author_image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/client3.png'),
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'Arlene McCoy',
                'description' => 'Excellent in terms of Safety, Handling and Performance in comparison with other hatchbacks. I have used i20 as well but its not even near to VW. Now using Altroz ',
                'label' => 'Nice work',
                'author_name' => 'Arlene McCoy',
                'author_image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/client3.png'),
            ]
        ];

        return $data;
    }

    public function getRecentStock()
    {
        $data = [];
        $data = [
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'CAR',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/work-img1.png'),
                'category' => 'Hatchback',
                'transmission' => 'Semi-Auto',
                'fuel' => 'Petrol',
                'bhp' => '285.6',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'CAR',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/work-img2.png'),
                'category' => 'Hatchback',
                'transmission' => 'Semi-Auto',
                'fuel' => 'Petrol',
                'bhp' => '285.6',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'CAR',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/work-img3.png'),
                'category' => 'Hatchback',
                'transmission' => 'Semi-Auto',
                'fuel' => 'Petrol',
                'bhp' => '285.6',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'CAR',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/work-img4.png'),
                'category' => 'Hatchback',
                'transmission' => 'Semi-Auto',
                'fuel' => 'Petrol',
                'bhp' => '285.6',
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'title' => 'CAR',
                'image' => asset('assets/web/template/' . $this->arg['template_slug'] . '/images/work-img5.png'),
                'category' => 'Hatchback',
                'transmission' => 'Semi-Auto',
                'fuel' => 'Petrol',
                'bhp' => '285.6',
            ]
        ];

        return $data;
    }

    public function getWorkingHours()
    {
        $data = [];
        $data = [
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'day' => 'sunday',
                'start_time' => '09:30:00',
                'end_time' => '18:00:00',
                'is_working' => 1,
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'day' => 'monday',
                'start_time' => '09:30:00',
                'end_time' => '18:00:00',
                'is_working' => 1,
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'day' => 'tuesday',
                'start_time' => '09:30:00',
                'end_time' => '18:00:00',
                'is_working' => 1,
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'day' => 'wednesday',
                'start_time' => '09:30:00',
                'end_time' => '18:00:00',
                'is_working' => 1,
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'day' => 'thursday',
                'start_time' => '09:30:00',
                'end_time' => '18:00:00',
                'is_working' => 1,
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'day' => 'friday',
                'start_time' => '09:30:00',
                'end_time' => '18:00:00',
                'is_working' => 1,
            ],
            [
                'user_id' => $this->arg['user_id'],
                'website_id' => $this->arg['website_id'],
                'day' => 'saturday',
                'start_time' => '09:30:00',
                'end_time' => '18:00:00',
                'is_working' => 1,
            ]
        ];
        return $data;
    }
}
